export const GET_ANALYTICS_PAGE_DETAILS = "GET_ANALYTICS_PAGE_DETAILS";
export const GET_ANALYTICS_PAGE_TIMELINE = "GET_ANALYTICS_PAGE_TIMELINE";

export const SET_ANALYTICS_PAGE_DETAILS = "SET_ANALYTICS_PAGE_DETAILS";
export const SET_ANALYTICS_PAGE_TIMELINE = "SET_ANALYTICS_PAGE_TIMELINE";
export const SET_ANALTICS_TRUNCATE = "SET_ANALTICS_TRUNCATE";