// RULES
export const SET_SELECTED_RULE = "SET_SELECTED_RULE";

// PRODUCTS
export const TRY_GET_PRODUCTS_LIST_FOR_ZONE_PRODUCTS = "TRY_GET_PRODUCTS_LIST_FOR_ZONE_PRODUCTS";
export const TRY_GET_PROPOSED_PRODUCTS_FOR_ZONE_PRODUCTS = "TRY_GET_PROPOSED_PRODUCTS_FOR_ZONE_PRODUCTS";
export const SET_PROPOSED_PRODUCTS_FOR_ZONE_PRODUCTS = "SET_PROPOSED_PRODUCTS_FOR_ZONE_PRODUCTS";
export const CLEAR_STORE = "CLEAR_STORE";
export const TRY_GET_PRODUCT_DATA_TO_EDIT = "TRY_GET_PRODUCT_DATA_TO_EDIT";
export const TRY_SET_PRODUCT_DATA_TO_EDIT = "TRY_SET_PRODUCT_DATA_TO_EDIT";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "SET_EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";
export const REPLACE_PRODUCT_REQUEST = "REPLACE_PRODUCT_REQUEST";
export const APP_PROCESS_STATUS = "APP_PROCESS_STATUS";
export const LINK_TO_ADS_STATUS = "LINK_TO_ADS_STATUS";
export const CREATE_TEST_STATUS = "CREATE_TEST_STATUS";

export const APP_SUCCESS_MESSAGE = "APP_SUCCESS_MESSAGE";
export const REPLACING_PRODUCT_LOADING_STATUS = "REPLACING_PRODUCT_LOADING_STATUS";
export const RESET_PUBLISH_SUCCESS_STATUS = "RESET_PUBLISH_SUCCESS_STATUS";
export const RESET_LINK_SUCCESS_STATUS = "RESET_LINK_SUCCESS_STATUS";
export const RESET_CREATE_SUCCESS_STATUS = "RESET_CREATE_SUCCESS_STATUS";
export const SET_PRODUCTS_LIST_FOR_ZONE_PRODUCTS = "SET_PRODUCTS_LIST_FOR_ZONE_PRODUCTS";
export const TRY_DELETE_PRODUCTS_LIST_FOR_ZONE_PRODUCTS = "TRY_DELETE_PRODUCTS_LIST_FOR_ZONE_PRODUCTS";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";

export const TRY_REORDER_PRODUCTS = "TRY_REORDER_PRODUCTS";
export const REORDER_PRODUCT_SUCCESS = "REORDER_PRODUCT_SUCCESS";

// KEYWORDS
export const TRY_GET_KEYWORDS_SUMMARY = "TRY_GET_KEYWORDS_SUMMARY";
export const SET_KEYWORDS_SUMMARY = "SET_KEYWORDS_SUMMARY";
export const TRY_GET_KEYWORDS_BY_CATEGORY = "TRY_GET_KEYWORDS_BY_CATEGORY";
export const SET_KEYWORDS_BY_CATEGORY = "SET_KEYWORDS_BY_CATEGORY";

// CAMPAINS
export const TRY_GET_RULE_CAMPAINS = "TRY_GET_RULE_CAMPAINS";
export const SET_RULE_CAMPAINS = "SET_RULE_CAMPAINS";
export const SET_SELECTED_CAMPAIN = "SET_SELECTED_CAMPAIN";

// PAGES
export const TRY_GET_PROPOSED_PAGES = "TRY_GET_PROPOSED_PAGES";
export const SET_PROPOSED_PAGES = "SET_PROPOSED_PAGES";
export const TRY_GET_DETAILS = "TRY_GET_DETAILS";
export const SET_PAGE_DETAILS = "SET_PAGE_DETAILS";
// FILTERS PRODUCTS
export const TRY_GET_PRODUCTS_FILTERS = "TRY_GET_PRODUCTS_FILTERS";
export const SET_PRODUCTS_FILTERS = "SET_PRODUCTS_FILTERS";
export const SET_DATA_TEXT_AREA = "SET_DATA_TEXT_AREA";
export const UPDATE_DATA_TEXT_AREA = "UPDATE_DATA_TEXT_AREA";
export const SET_SUCESS_DATA_TEXT_AREA = "SET_SUCESS_DATA_TEXT_AREA";
export const RESET_DATA_TEXT_AREA = "RESET_DATA_TEXT_AREA";

// ADD PRODUCT TO PAGE
export const TRY_ADD_PRODUCTS_TO_PAGE = "TRY_ADD_PRODUCTS_TO_PAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const TRY_PUBLISH_PAGES = "TRY_PUBLISH_PAGES";
export const TRY_PUBLISH_PAGES_SUCESS = "TRY_PUBLISH_PAGES_SUCESS";
export const TRY_LINK_PAGES_SUCESS = "TRY_LINK_PAGES_SUCESS";

// CAMPAIGN TEST
export const TRY_GET_CAMPAIGN_TEST_BY_KEYWORD = "TRY_GET_CAMPAIGN_TEST_BY_KEYWORD";
export const TRY_GET_CAMPAIGN_TEST_BY_KEYWORD_SUCESS = "TRY_GET_CAMPAIGN_TEST_BY_KEYWORD_SUCESS";
export const SET_CAMPAIGN_TEST_BY_KEYWORD = "SET_CAMPAIGN_TEST_BY_KEYWORD";
export const RESET_CAMPAIGN_TEST_BY_KEYWORD = "RESET_CAMPAIGN_TEST_BY_KEYWORD";
export const TRY_POST_CREATE_CAMPAIGN_TEST = "TRY_POST_CREATE_CAMPAIGN_TEST";
export const CREATE_CAMPAIGN_TEST = "CREATE_CAMPAIGN_TEST";
export const CREATE_NEW_CAMPAIGN_TEST = "CREATE_NEW_CAMPAIGN_TEST";
export const TRY_POST_LINK_PAGE_TO_ADWORDS = "TRY_POST_LINK_PAGE_TO_ADWORDS";
export const TRY_POST_LINK_PAGE_TO_ADWORDS_SUCESS = "TRY_POST_LINK_PAGE_TO_ADWORDS_SUCESS";

// TEXT AREA
export const TRY_GET_TXT_CONTENT_BY_ZONE = "TRY_GET_TXT_CONTENT_BY_ZONE";
export const SET_TXT_CONTENT_BY_ZONE = "SET_TXT_CONTENT_BY_ZONE";
export const TRY_GET_TXT_PROPOSALS_ZONE = "TRY_GET_TXT_PROPOSALS_ZONE";
export const SET_SELECTED_KEYWORD = "SET_SELECTED_KEYWORD";
export const SET_NEXT_SELECTED_INDEX = "SET_NEXT_SELECTED_INDEX";
export const SET_SELECTED_LABEL = "SET_SELECTED_LABEL";
export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const SET_TXT_PROPOSALS_ZONE = "SET_TXT_PROPOSALS_ZONE";

export const ZONE_TYPE_TITLE = "title";
export const ZONE_TYPE_DESCRIPTION = "description";
export const ZONE_TYPE_IMAGES = "images";

/* filters */
export const SET_FILTERS = "SET_FILTERS";
export const REPLACE_FILTER = "REPLACE_FILTER";
export const DELETE_FILTER = "DELETE_FILTER";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
